poanetwork/parity-ethereum

Cargo.lock, ethcore/Cargo.toml, ethcore/src/engines/hbbft/mod.rs, json/src/spec/hbbft.rs
- Added a `.on_new_block()` method to the `Hbbft` engine to call the POA network consensus contract's `finalizeChange` function.
- Added a `.on_close_block()` method to the `Hbbft` engine to apply block rewards.
- Added new config options to the `Hbbft` engine's JSON spec.
- Updated `hydrabadger` dependency to use `master` (`hydrabadger:master` now includes the sender-queue).
- Added docs to the `Hbbft` engine.
=> Added 'on_new_block' and 'on_close_block' implemenetations to Hbbft engine

ethcore/res/ethereum/poaindica.json, ethcore/res/hbbft.json, ethcore/src/engines/hbbft/mod.rs, json/src/spec/hbbft.rs
GitLab CI runs a a series of tests to ensure that all chainspecs in `ethcore/res/*.json` and `ethcore/res/ethereum/*.json` are valid. The `hbbft` and `poaindica` chainspecs are currently parse-able (i.e. don't make `cargo build` fail), but are not  totally valid. This PR fixes fixes the failing chainspec tests.
This PR includes spelling fixes for the Hbbft engine docs and the Hbbft JSON spec docs.
=> Fix failing chainspec tests for the 'hbbft' and 'poaindica' chainspecs

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/hbbft/mod.rs, ethcore/src/engines/mod.rs, ethcore/src/engines/validator_set/safe_contract.rs
`Hbbft::get_validator_set_at_block()` is used to read, decode, and extract the validator addresses from the validator-set transition proof stored in the blockchain database for a given block.
Added documentation to:
- `ethcore/src/engines/authority_round/mod.rs`
- `ethcore/src/engines/validator_set/safe_contract.rs`
=> Added 'get_validator_set_at_block' to Hbbft engine

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/validator_set/contract.rs, ethcore/src/engines/validator_set/mod.rs, ethcore/src/engines/validator_set/multi.rs
- The `signer` argument of `report_malicious`:
- The argument of `signer` is made immutable.
- The result of `signer` now contains the `Error`.
- This `Error` is returned from the caller of `report_malicious` instead of being discarded in a call to `expect`.
=> Minor changes in reporting malicious validator in AuRa

ethcore/res/contracts/authority_round_random.json, ethcore/res/contracts/validator_set.json, ethcore/src/engines/authority_round/randomness.rs, ethcore/src/engines/validator_set/contract.rs, ethcore/src/engines/validator_set/mod.rs, ethcore/src/engines/validator_set/safe_contract.rs, json/src/spec/authority_round.rs, json/src/spec/validator_set.rs, test.sh
instead of relying on the `InitiateChange` event.
Closes #49.
=> Call `get_pending_validators`

ethcore/src/engines/validator_set/mod.rs, ethcore/src/engines/validator_set/safe_contract.rs
I had assumed that Proof of Stake (PoS) was the current consensus
algorithm and Proof of Authority (PoA) was the new one, but in reality,
the opposite is the case.
=> Flip `ConsensusKind::Poa` and `ConsensusKind::Pos` where needed

Cargo.lock, ethcore/Cargo.toml, ethcore/res/contracts/hbbft/key_gen_history.json, ethcore/res/contracts/hbbft/test_junk_contract.json, ethcore/src/engines/mod.rs, ethcore/src/hbbft/daemon.rs, ethcore/src/hbbft/key_gen.rs, ethcore/src/hbbft/laboratory.rs, ethcore/src/hbbft/mod.rs, ethcore/src/lib.rs
Runs a `SyncKeyGen` instance using the blockchain as the communications channel.
=> [WIP] Implement on-chain key generation

ethcore/src/engines/block_reward.rs, ethcore/src/engines/mod.rs
`EngineError::FailedSystemCall` was used to denote 3 different kinds of error in `block_reward.rs`. This PR corrects that.
=> Use more informative error variants for FailedSystemCall

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/authority_round/randomness.rs, ethcore/src/engines/authority_round/util.rs
`Engine::on_new_block` is called multiple times, so we need to
remember which round a random secret is for, and generate a new one
only in the following round. `on_block_new` also mustn't fail if
the same transaction is produced again.
Closes #67.
=> Fix randomness secret.

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/mod.rs
Cosmetic changes to introduce a dedicated `EngineError` variants for `PhaseError`s produced by `authority_round/randomness` module.
Can probably be handled better in the future.
=> Add EngineError variants for randomness errors

ethcore/res/contracts/authority_round_random.json, ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/authority_round/util.rs
The contract seems to have a duplicate entry. This replaces it
with the generated ABI.
`Client::transact` sometimes fails with and `Old` error, meaning
the nonce is outdated. This will now just log an error instead of
making block creation fail. The `schedule_service_transaction`
method might get removed in the future anyway, if we make
`ValidatorSet::on_new_block` _return_ the transaction instead of
queueing it.
=> Cleanup rand contract, improve error handling.

ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/engines/authority_round/mod.rs
That solves the issue of the gas limit, where we'd otherwise pick
some arbitrary large value, and the chain ID, which now conforms
to EIP155 again.
=> Move transaction creation back into the client.

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/basic_authority.rs, ethcore/src/engines/mod.rs, ethcore/src/engines/tendermint/mod.rs, ethcore/src/miner/miner.rs, ethcore/src/miner/mod.rs, rpc/src/v1/impls/light/parity_set.rs, rpc/src/v1/impls/parity_set.rs, rpc/src/v1/tests/helpers/miner_service.rs, rpc/src/v1/traits/parity_set.rs
=> RPC method parity_clearEngineSigner

Cargo.lock
`cargo build` in `ethcore/hbbft_engine` was failing due to conflicting rand_core versions.
=> Update rand_core to fix the build.

ethcore/src/client/chain_notify.rs, ethcore/src/client/client.rs, ethcore/src/test_helpers.rs, ethcore/sync/src/api.rs
In contrast to `ChainNotify::broadcast`, this is meant to send a message to a specific peer.
=> Add ChainNotify::send.

Cargo.lock, ethcore/Cargo.toml, ethcore/hbbft_engine/Cargo.toml, ethcore/hbbft_engine/res/honey_badger_bft.json, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs, ethcore/hbbft_engine/tests/p2p.rs, ethcore/src/client/test_client.rs, ethcore/src/engines/mod.rs, ethcore/src/engines/registry.rs, ethcore/src/lib.rs, ethcore/src/spec/spec.rs, json/src/spec/engine.rs
This allows implementing the `Engine` trait in a crate other than `ethcore`, and configuring it in the chain spec.
Unfortunately the tests only work if the `inventory::submit!` call is in the test file itself. The call in `lib.rs` seems to have no effect, and leaves the iterator empty. I added a `TODO` for now.
=> Add a registry for external engine implementations.

Cargo.lock, ethcore/hbbft_engine/Cargo.toml, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs, ethcore/hbbft_engine/src/test_helpers.rs, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/engines/mod.rs, ethcore/src/miner/miner.rs
Added a "on_transactions_imported()" function to the Consensus Engine trait, called after successful import of new transactions.
Also added a "queued_transactions()" function to the EngineClient trait to query queued transactions.
Using "queued_transactions()" to trigger the creation of a new block when the transaction queue length trigger is reached (currently set to 1)
Registering the Client instance with the hbbft Consensus Engine in test helpers to be able to access EngineClient functions.
=> Notifying Parity Consensus Engines about Transaction Queue changes

ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/mod.rs, ethcore/src/miner/miner.rs
Added create_pending_block() function to the EngineClient trait and implemented the function in Miner.
Using this function in the hbbft Engine implementation when the threshold number of queued Transactions is reached.
(Re)added the should_miner_prepare_blocks() function to the Engine trait. Used it to make "prepare_block" only return pending blocks or None if no pending blocks are available in the case of should_miner_prepare_blocks() returning false.
=> Engine creates Block with chosen Transactions

Cargo.lock, ethcore/Cargo.toml, ethcore/hbbft_engine/Cargo.toml, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs, ethcore/hbbft_engine/src/test_helpers.rs, ethcore/light/Cargo.toml, ethcore/light/src/client/mod.rs, ethcore/light/src/lib.rs, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/lib.rs
Made a NetworkInfo struct instance required for initializing hbbft algorithms available to Parity consensus engines via the EngineClient trait.
This introduces a temporary dependency on the hbbft crate to the "ethcore" and "light" crates which can be removed as soon as validator bootstrapping and management is available via specs and smart contracts.
=> Environment for initializing hbbft algorithms in the HoneyBadgerBFT Parity consensus engine

ethcore/src/client/client.rs, ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/basic_authority.rs, ethcore/src/engines/instant_seal.rs, ethcore/src/engines/mod.rs, ethcore/src/miner/miner.rs
This prevents the miner from creating new blocks for sealing even if it's not our turn to seal them.
However, it likely does not detect all cases yet where it's not our turn.
(Closes #70.)
=> Add SealingState; don't prepare block when not ready.

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/validator_set/contract.rs, ethcore/src/engines/validator_set/safe_contract.rs
1. ~~Removed instantaneous calls to `reportMalicious`.~~
2. Added a gap of at least one block after reporting malicious validators and before reporting more malicious validators.
=> Skip a block when reporting malicious validators

ethcore/src/engines/authority_round/mod.rs, json/src/spec/authority_round.rs, json/src/spec/mod.rs, json/src/spec/step_duration.rs
=> Allow specifying stepDuration as a map.

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/validator_set/contract.rs, ethcore/src/engines/validator_set/mod.rs, ethcore/src/engines/validator_set/safe_contract.rs, json/src/spec/authority_round.rs
Fixes #141.
This PR can be tested with https://github.com/poanetwork/posdao-test-setup/tree/posdao-transition
=> posdaoTransition spec option

ethcore/call-contract/src/call_contract.rs, ethcore/private-tx/src/key_server_keys.rs, ethcore/res/contracts/block_gas_limit.json, ethcore/res/contracts/tx_acl_gas_price.json, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/mod.rs, ethcore/src/machine.rs, ethcore/src/spec/spec.rs, ethcore/src/tx_filter.rs, ethcore/src/verification/verification.rs, json/src/spec/params.rs
WIP: This passes the [`posdao-test-setup`](https://github.com/poanetwork/posdao-test-setup), but both the low and the regular gas limits are still hard-coded, and the call in `verify_header_params` uses the wrong header at the moment. (See TODOs.)
It also extends the `Engine` trait in a way that's not exactly sane. And it doesn't allow for a variable gas limit.
And crucially, I don't know yet whether the state of the block hash that we use for the `limitBlockGas` call is always available in the client's database, especially if there's a fork; or whether and how this will work together with snapshots and warp sync.
Closes #119.
=> Set gas limit according to TxPermission.blockGasLimit.

Cargo.lock, ethcore/hbbft_engine/hbbft_config_generator/Cargo.toml, ethcore/hbbft_engine/hbbft_config_generator/src/main.rs, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs
To register reserved_peers we need the public key, the ip address and the port formatted in the "enode://" format.
The corresponding secret key is also generated and written to disk alongside the hbbft test net node.toml files.
Other noteworthy changes:
Extracted network simulator function to perform single cranks in order to set up more sophisticated test scenarios.
Implemented a test for joining a new epoch after receiving f+1 contributions.
=> Generating enode://... strings for hbbft test net validators and supplying them as hbbft toml option

ethcore/hbbft_engine/hbbft_config_generator/src/main.rs, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs, ethcore/hbbft_engine/src/test_helpers.rs, ethcore/light/src/client/mod.rs, ethcore/src/client/chain_notify.rs, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/mod.rs, ethcore/src/test_helpers.rs, ethcore/sync/src/api.rs, ethcore/sync/src/chain/handler.rs
Eliminated the redundant "peer_id" argument from consensus message sending/receiving functions as well.
=> Using the parity node id as hbbft NetworkInfo "our_id" type in the HoneyBadgerBFT Engine and toml config generator

Cargo.lock, ethcore/hbbft_engine/Cargo.toml, ethcore/hbbft_engine/res/honey_badger_bft.json, ethcore/hbbft_engine/src/contribution.rs, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs, ethcore/light/src/client/mod.rs, ethcore/src/client/client.rs, ethcore/src/client/test_client.rs, ethcore/src/client/traits.rs, ethcore/src/miner/miner.rs
* Implemented create_pending_block_at() function to assure a new block is created with the desired parent. Avoids creating a block which already has been imported through gossip from other validator nodes.
* Added and implemented options to configure a minimum block time to avoid TimestampOverflow errors.
* Implemented handling of Target::AllExcept hbbft messages.
Note: Make sure to configure the node.toml "reseal_min_period" mining setting to a setting lower than the "minimumBlockTime" HoneyBadgerBFT chain spec setting, or the value "reseal_min_period" will restrict your minimum block time.
=> Stabilized HoneyBadgerBFT Engine

ethcore/src/engines/authority_round/mod.rs, ethcore/src/spec/spec.rs, json/src/spec/authority_round.rs, json/src/spec/params.rs
This is a backport from https://github.com/paritytech/parity-ethereum/pull/10928.
The new name of the parameter is `blockGasLimitContractTransitions`. @varasev, @phahulin, please use the new name in spec files.
=> Move blockGasLimitContract to AuRa params and rename it

Cargo.lock, ethcore/hbbft_engine/Cargo.toml, ethcore/hbbft_engine/src/hbbft_engine.rs, ethcore/hbbft_engine/src/lib.rs
This shortens node IDs in `Debug` output, which otherwise would print all 128 hex digits. It now looks like this: `proposer_id: be..77`.
=> Ellipsize NodeId hex digits in Debug.

ethcore/engine/src/engine.rs, ethcore/engines/hbbft/src/hbbft_engine.rs, ethcore/src/miner/miner.rs
Setting the "engine_signer" in the parity mining options also sets the address as the author of blocks produced by the validator. This causes generated blocks to differ between validators, and sealing to fail.
Added an option to the Engine trait to signal that the "engine_signer" should *not* be used as block author.
=> Added an option to the Engine trait to use the author only as engine signer

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/validator_set/test.rs
Backport of https://github.com/paritytech/parity-ethereum/pull/11160
=> Report malice on sibling blocks from the same validator

ethcore/src/engines/authority_round/mod.rs, ethcore/src/engines/basic_authority.rs, ethcore/src/engines/clique/mod.rs, ethcore/src/engines/mod.rs, ethcore/src/miner/miner.rs, ethcore/src/miner/mod.rs, rpc/src/v1/impls/parity_set.rs, rpc/src/v1/tests/helpers/miner_service.rs
Original commit messages:
RPC method parity_clearEngineSigner
Add RPC method parity_clearEngineSigner
Fixes https://github.com/poanetwork/parity-ethereum/issues/113
corrected the return type of clear_author
review comment responses and a rebase fix
removed a spurrious warning
moved clear_signer functionality to set_signer
Merge clear_author into MinerService::set_author.
Add trace logs to Clique::set_signer.
Clique: Don't lock signer multiple times.
=> Backport upstream's impl to clear engine signer.
